import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const read = (path) => readFileSync(join(root, path), 'utf8');

const checks = [
  ['src/main.jsx', 'Kindred Pages'],
  ['src/main.jsx', 'routeFromPath'],
  ['src/main.jsx', 'getRouteMetadata'],
  ['src/main.jsx', 'upsertMeta'],
  ['src/main.jsx', 'upsertCanonical'],
  ['src/main.jsx', 'document.title = metadata.title'],
  ['scripts/prerender-routes.mjs', 'Prerendered'],
  ['scripts/prerender-routes.mjs', '/builder'],
  ['scripts/prerender-routes.mjs', '/templates'],
  ['scripts/prerender-routes.mjs', 'sitemap.xml'],
  ['package.json', 'scripts/prerender-routes.mjs'],
  ['src/main.jsx', "['/builder', '/templates', '/preview', '/pricing', '/partners', '/trust']"],
  ['src/main.jsx', 'HomeWorkflow'],
  ['src/main.jsx', 'HomeAudienceMap'],
  ['src/main.jsx', 'Built for the whole memorial loop'],
  ['src/main.jsx', 'Family admin'],
  ['src/main.jsx', 'Family archive'],
  ['src/main.jsx', 'TemplatesPage'],
  ['src/main.jsx', 'Choose the memorial shape before touching the builder'],
  ['src/main.jsx', 'Fast choice guide'],
  ['src/main.jsx', 'Use the most common setup'],
  ['src/main.jsx', 'Defaults reduce decisions, but families keep control'],
  ['src/main.jsx', 'PreviewProof'],
  ['src/main.jsx', 'What this preview proves'],
  ['src/main.jsx', 'It is not just a pretty page'],
  ['src/main.jsx', 'Public tasks'],
  ['src/main.jsx', 'Build this page'],
  ['src/main.jsx', 'PricingPage'],
  ['src/main.jsx', 'PricingGuidance'],
  ['src/main.jsx', 'PricingDecisionGuide'],
  ['src/main.jsx', 'Choose without a sales call'],
  ['src/main.jsx', 'What happens after payment'],
  ['src/main.jsx', 'What the purchase covers'],
  ['src/main.jsx', 'PartnerMarketingPage'],
  ['src/main.jsx', 'Partner workflow'],
  ['src/main.jsx', 'Partner value stack'],
  ['src/main.jsx', 'What the care team can hand off'],
  ['src/main.jsx', 'Package reporting'],
  ['src/main.jsx', 'Less repeated coordination'],
  ['src/main.jsx', 'A sellable digital add-on'],
  ['src/main.jsx', 'Respectful boundaries'],
  ['src/main.jsx', 'TrustResearchPage'],
  ['src/main.jsx', 'Private by default'],
  ['src/main.jsx', 'Sensitive review'],
  ['src/main.jsx', 'Bereavement biography'],
  ['src/main.jsx', 'Bell, Bailey, and Kennedy'],
  ['src/main.jsx', 'id="page-content" className="trust-center"'],
  ['src/main.jsx', 'aria-current={route === path ? \'page\' : undefined}'],
  ['src/styles.css', '.site-nav'],
  ['src/styles.css', '.home-audience'],
  ['src/styles.css', '.audience-grid'],
  ['src/styles.css', '.templates-page'],
  ['src/styles.css', '.template-choice-grid'],
  ['src/styles.css', '.template-research'],
  ['src/styles.css', '.preview-proof'],
  ['src/styles.css', '.guest-job-grid'],
  ['src/styles.css', '.preview-proof-actions'],
  ['src/styles.css', '.workflow-grid'],
  ['src/styles.css', '.pricing-decision'],
  ['src/styles.css', '.decision-table'],
  ['src/styles.css', '.after-pay-card'],
  ['src/styles.css', '.pricing-hero'],
  ['src/styles.css', '.pricing-fit-grid'],
  ['src/styles.css', '.pricing-faq'],
  ['src/styles.css', '.partner-landing'],
  ['src/styles.css', '.partner-flow'],
  ['src/styles.css', '.partner-outcomes'],
  ['src/styles.css', '.partner-value-grid'],
  ['src/styles.css', '.partner-artifact-grid'],
  ['src/styles.css', '.safeguard-grid'],
  ['src/styles.css', '.research-grid span'],
  ['src/styles.css', '.research-grid'],
  ['README.md', 'Multi-page product experience'],
  ['README.md', 'Home page audience map'],
  ['README.md', 'Templates page with situation-specific starting points'],
  ['README.md', 'Preview proof section'],
  ['README.md', 'Pricing decision guide'],
  ['README.md', 'plan-fit guidance'],
  ['README.md', 'Partner value stack'],
  ['README.md', 'intake-to-handoff workflow'],
  ['README.md', 'peer-reviewed evidence mapped to product choices'],
  ['README.md', 'Route-specific page titles'],
  ['README.md', 'Static post-build route shells'],
  ['index.html', 'twitter:card'],
  ['index.html', 'rel="canonical"'],
  ['public/sitemap.xml', 'https://kindred-pages-wine.vercel.app/builder'],
  ['public/sitemap.xml', 'https://kindred-pages-wine.vercel.app/templates'],
  ['public/sitemap.xml', 'https://kindred-pages-wine.vercel.app/partners'],
  ['docs/production-checklist.md', '`/builder`, `/templates`, `/preview`, `/pricing`, `/partners`, and `/trust`'],
  ['docs/production-checklist.md', '`/` immediately shows the niche'],
  ['docs/production-checklist.md', '`/templates` lets a family choose'],
  ['docs/production-checklist.md', '`/preview` shows guest tasks'],
  ['docs/production-checklist.md', '`/pricing` helps families and funeral homes choose a plan'],
  ['docs/production-checklist.md', '`/pricing` explains which plan fits'],
  ['docs/production-checklist.md', '`/partners` explains the funeral-home workflow'],
  ['docs/production-checklist.md', '`/partners` shows package fit'],
  ['docs/production-checklist.md', '`/trust` explains privacy safeguards'],
  ['docs/production-checklist.md', 'Open Graph, and Twitter preview metadata'],
  ['docs/production-checklist.md', 'social crawlers receive static metadata'],
  ['docs/research-rationale.md', 'multi-page structure reduces cognitive load'],
  ['docs/research-rationale.md', 'family-readable safeguards'],
  ['.env.example', 'VITE_SUPABASE_URL'],
  ['src/main.jsx', 'loadSiteDraft'],
  ['src/main.jsx', 'saveSiteDraft'],
  ['src/persistence.js', 'VITE_DRAFT_ENDPOINT'],
  ['src/persistence.js', 'saveSiteDraft'],
  ['src/persistence.js', 'local-fallback'],
  ['src/persistence.js', 'Protected draft'],
  ['src/main.jsx', 'Skip to builder'],
  ['src/main.jsx', 'stepFromHash'],
  ['src/main.jsx', 'openStep'],
  ['src/main.jsx', 'getStepStatuses'],
  ['src/main.jsx', 'stepStatuses'],
  ['src/main.jsx', 'BuilderStartGuide'],
  ['src/main.jsx', 'First three decisions'],
  ['src/main.jsx', 'Start simple. The rest can wait.'],
  ['src/main.jsx', 'step-state'],
  ['src/main.jsx', 'hashchange'],
  ['src/main.jsx', 'aria-current'],
  ['src/main.jsx', 'aria-pressed'],
  ['src/main.jsx', 'role="progressbar"'],
  ['src/main.jsx', 'kindred-hero.jpg'],
  ['src/main.jsx', 'normalizePhotos'],
  ['src/main.jsx', 'coverPhoto'],
  ['src/main.jsx', 'publicPhotos'],
  ['src/main.jsx', 'setCoverPhoto'],
  ['src/main.jsx', 'Caption or names'],
  ['src/main.jsx', 'Family cover photo'],
  ['src/main.jsx', 'Family Desk'],
  ['src/main.jsx', 'Guided Setup'],
  ['src/main.jsx', 'gatheringPresets'],
  ['src/main.jsx', 'applyGatheringPreset'],
  ['src/main.jsx', 'Gathering type selected'],
  ['src/main.jsx', 'Online Remembrance'],
  ['src/main.jsx', 'Private Family Archive'],
  ['src/styles.css', '.setup-presets'],
  ['src/styles.css', '.preset-grid'],
  ['src/styles.css', '.preset-card'],
  ['src/styles.css', '.step-state'],
  ['src/main.jsx', 'Copy share link'],
  ['src/main.jsx', 'activityLog'],
  ['src/main.jsx', 'addActivity'],
  ['src/main.jsx', 'VITE_AUDIT_ENDPOINT'],
  ['src/main.jsx', 'auditEndpoint'],
  ['src/main.jsx', 'Activity'],
  ['src/main.jsx', 'Memory approved'],
  ['src/main.jsx', 'rejectMemory'],
  ['src/main.jsx', 'rejectedMemories'],
  ['src/main.jsx', 'Keep private'],
  ['src/main.jsx', 'Memory declined'],
  ['src/main.jsx', 'Archive exported'],
  ['src/main.jsx', 'Page published'],
  ['src/main.jsx', 'Family Helpers'],
  ['src/main.jsx', 'addCoadmin'],
  ['src/main.jsx', 'coadminInviteText'],
  ['src/main.jsx', 'copyCoadminInvite'],
  ['src/main.jsx', 'Partner Desk'],
  ['src/main.jsx', 'Announcements'],
  ['src/main.jsx', 'AnnouncementEditor'],
  ['src/main.jsx', 'Guest Updates'],
  ['src/main.jsx', 'guestUpdates'],
  ['src/main.jsx', 'addGuestUpdate'],
  ['src/main.jsx', 'urgentUpdates'],
  ['src/main.jsx', 'urgent-toggle'],
  ['src/main.jsx', 'Urgent update:'],
  ['src/main.jsx', 'obituaryPlacements'],
  ['src/main.jsx', 'addObituaryPlacement'],
  ['src/main.jsx', 'updateObituaryPlacementStatus'],
  ['src/main.jsx', 'Obituary Publishing'],
  ['src/main.jsx', 'Publication tracker'],
  ['src/main.jsx', 'Newspaper notice'],
  ['src/main.jsx', 'Livestream reminder'],
  ['src/main.jsx', 'Support the Family'],
  ['src/main.jsx', 'addSupportGift'],
  ['src/main.jsx', 'supportNeeds'],
  ['src/main.jsx', 'addSupportNeed'],
  ['src/main.jsx', 'claimSupportNeed'],
  ['src/main.jsx', 'Support Needs'],
  ['src/main.jsx', 'Claim'],
  ['src/main.jsx', 'support needs, claimants, and status'],
  ['src/main.jsx', 'Open third-party link'],
  ['src/main.jsx', 'Opens outside Kindred Pages'],
  ['src/main.jsx', 'partnerDrafts'],
  ['src/main.jsx', 'markHandoffReady'],
  ['src/main.jsx', 'Guest Care'],
  ['src/main.jsx', 'Access Controls'],
  ['src/main.jsx', 'Archive & Closure'],
  ['src/main.jsx', 'Family archive manifest'],
  ['src/main.jsx', 'retentionPlan'],
  ['src/main.jsx', 'closureStatus'],
  ['src/main.jsx', 'closureRequests'],
  ['src/main.jsx', 'addClosureRequest'],
  ['src/main.jsx', 'updateClosureRequestStatus'],
  ['src/main.jsx', 'closurePacketText'],
  ['src/main.jsx', 'Copy closure packet'],
  ['src/main.jsx', 'inviteToken'],
  ['src/main.jsx', 'allowGuestSharing'],
  ['src/main.jsx', 'searchVisibility'],
  ['src/main.jsx', 'GuestAccessGate'],
  ['src/main.jsx', 'Private memorial'],
  ['src/main.jsx', 'accessUnlocked'],
  ['src/main.jsx', 'VITE_ACCESS_ENDPOINT'],
  ['src/main.jsx', 'accessEndpoint'],
  ['src/main.jsx', 'VITE_AUTH_ENDPOINT'],
  ['src/main.jsx', 'requestAdminAccess'],
  ['src/main.jsx', 'Admin Access'],
  ['src/main.jsx', 'Launch command center'],
  ['src/main.jsx', 'Launch Readiness Report'],
  ['src/main.jsx', 'launchReadinessReportText'],
  ['src/main.jsx', 'copyLaunchReadinessReport'],
  ['src/main.jsx', 'downloadLaunchReadinessReport'],
  ['src/main.jsx', 'Next action'],
  ['src/main.jsx', 'Family Launch Approval'],
  ['src/main.jsx', 'launchApproval'],
  ['src/main.jsx', 'approvalComplete'],
  ['src/main.jsx', 'copyFamilyApprovalPacket'],
  ['src/main.jsx', 'Mark approved'],
  ['src/main.jsx', 'Copy approval packet'],
  ['src/main.jsx', 'Family Ownership Handoff'],
  ['src/main.jsx', 'familyHandoffPacketText'],
  ['src/main.jsx', 'copyFamilyHandoffPacket'],
  ['src/main.jsx', 'Family ownership handoff'],
  ['src/main.jsx', 'Copy handoff packet'],
  ['src/styles.css', '.handoff-panel'],
  ['src/styles.css', '.handoff-grid'],
  ['src/main.jsx', 'Privacy & Sharing Review'],
  ['src/main.jsx', 'privacyReview'],
  ['src/main.jsx', 'privacyReviewComplete'],
  ['src/main.jsx', 'togglePrivacyReviewCheck'],
  ['src/main.jsx', 'updatePrivacyReview'],
  ['src/main.jsx', 'markPrivacyReviewed'],
  ['src/main.jsx', 'privacy and sharing review'],
  ['src/styles.css', '.privacy-review-panel'],
  ['src/styles.css', '.privacy-review-grid'],
  ['src/styles.css', '.privacy-review-check'],
  ['src/main.jsx', 'Sensitive Details Review'],
  ['src/main.jsx', 'sensitiveReview'],
  ['src/main.jsx', 'sensitiveReviewComplete'],
  ['src/main.jsx', 'toggleSensitiveReviewCheck'],
  ['src/main.jsx', 'updateSensitiveReview'],
  ['src/main.jsx', 'markSensitiveReviewed'],
  ['src/main.jsx', 'Cause-of-death'],
  ['src/main.jsx', 'Sensitive details reviewed'],
  ['src/main.jsx', 'Record sensitive details review first'],
  ['src/styles.css', '.sensitive-review-panel'],
  ['src/styles.css', '.sensitive-review-grid'],
  ['src/styles.css', '.sensitive-review-check'],
  ['src/main.jsx', 'planCatalog'],
  ['src/main.jsx', 'getPlanDetails'],
  ['src/main.jsx', 'VITE_MEDIA_ENDPOINT'],
  ['src/main.jsx', 'planMediaStorage'],
  ['src/main.jsx', 'Photo storage needs setup'],
  ['src/main.jsx', 'uploadStatus'],
  ['src/main.jsx', 'VITE_INVITE_ENDPOINT'],
  ['src/main.jsx', 'invitePayload'],
  ['src/main.jsx', 'inviteBatchText'],
  ['src/main.jsx', 'Invite endpoint needs setup'],
  ['src/main.jsx', 'checkoutPacketText'],
  ['src/main.jsx', 'copyCheckoutPacket'],
  ['src/main.jsx', 'Copy checkout packet'],
  ['src/main.jsx', 'Share Preview'],
  ['src/main.jsx', 'Accessibility Review'],
  ['src/main.jsx', 'accessibilityChecks'],
  ['src/main.jsx', 'toggleAccessibilityCheck'],
  ['src/main.jsx', 'Accessibility review complete'],
  ['src/main.jsx', 'shareMetadata'],
  ['src/main.jsx', 'copyShareMetadata'],
  ['src/main.jsx', 'Share metadata copied'],
  ['src/main.jsx', 'robots'],
  ['src/main.jsx', 'canonicalUrl'],
  ['src/main.jsx', 'openGraphType'],
  ['src/main.jsx', 'Production Integrations'],
  ['src/main.jsx', 'IntegrationCard'],
  ['src/main.jsx', 'integrationChecks'],
  ['src/styles.css', '.admin-access-panel'],
  ['src/styles.css', '.admin-access-grid'],
  ['src/main.jsx', 'VITE_STRIPE_CHECKOUT_URL'],
  ['src/main.jsx', 'VITE_PUBLISH_ENDPOINT'],
  ['src/main.jsx', 'startCheckout'],
  ['src/main.jsx', 'publishPage'],
  ['src/main.jsx', 'sendInvites'],
  ['src/main.jsx', 'eventSchedule'],
  ['src/main.jsx', 'careContacts'],
  ['src/main.jsx', 'livestreamPlan'],
  ['src/main.jsx', 'updateLivestreamPlan'],
  ['src/main.jsx', 'Livestream & Recording'],
  ['src/main.jsx', 'Watch Online'],
  ['src/main.jsx', 'Open replay'],
  ['src/main.jsx', 'livestream platform, replay, recording, and backup plan'],
  ['src/main.jsx', 'guestFaq'],
  ['src/main.jsx', 'addGuestFaq'],
  ['src/main.jsx', 'Guest FAQ'],
  ['src/main.jsx', 'customCare'],
  ['src/main.jsx', 'addCustomCare'],
  ['src/main.jsx', 'Custom & Ritual Care'],
  ['src/main.jsx', 'custom, ritual, faith, and family guidance'],
  ['src/main.jsx', 'dayOfChecklist'],
  ['src/main.jsx', 'addDayOfTask'],
  ['src/main.jsx', 'toggleDayOfTask'],
  ['src/main.jsx', 'dayOfPacketText'],
  ['src/main.jsx', 'downloadDayOfPacket'],
  ['src/main.jsx', 'Day-of Service Packet'],
  ['src/main.jsx', 'coordinatorBriefText'],
  ['src/main.jsx', 'Coordinator Brief'],
  ['src/main.jsx', 'Copy brief'],
  ['src/styles.css', '.coordinator-brief'],
  ['src/styles.css', '.coordinator-brief-grid'],
  ['src/styles.css', '.brief-list'],
  ['src/main.jsx', 'aftercareReminders'],
  ['src/main.jsx', 'anniversaryCare'],
  ['src/main.jsx', 'addAnniversaryCare'],
  ['src/main.jsx', 'updateAnniversaryStatus'],
  ['src/main.jsx', 'Anniversary Care'],
  ['src/main.jsx', 'Anniversary message'],
  ['src/main.jsx', 'anniversary care message drafts and status'],
  ['src/main.jsx', 'thankYouList'],
  ['src/main.jsx', 'addThankYouRecipient'],
  ['src/main.jsx', 'toggleThankYouSent'],
  ['src/main.jsx', 'Thank-you Tracker'],
  ['src/main.jsx', 'Thank-you tracker updated'],
  ['src/main.jsx', 'aftercarePacketText'],
  ['src/main.jsx', 'copyAftercarePacket'],
  ['src/main.jsx', 'Aftercare Packet'],
  ['src/main.jsx', 'Copy aftercare packet'],
  ['src/main.jsx', 'Share a Memory'],
  ['src/main.jsx', 'guestNotice'],
  ['src/main.jsx', 'rsvpNotice'],
  ['src/main.jsx', 'supportNotice'],
  ['src/main.jsx', 'guest-confirmation'],
  ['src/main.jsx', 'Your memory was sent privately to the family for review'],
  ['src/styles.css', '.guest-confirmation'],
  ['src/main.jsx', 'public-action-bar'],
  ['src/main.jsx', 'Guest actions'],
  ['src/main.jsx', 'moveGuestTo'],
  ['src/main.jsx', 'contribution-box'],
  ['src/main.jsx', 'support-section'],
  ['src/styles.css', '.public-action-bar'],
  ['src/main.jsx', 'Attach a photo'],
  ['src/main.jsx', 'Attach a voice note'],
  ['src/main.jsx', 'guestAudioLabel'],
  ['src/main.jsx', 'guestPhotoCaption'],
  ['src/main.jsx', 'guestRelation'],
  ['src/main.jsx', 'guestConsent'],
  ['src/main.jsx', 'sent to the family for review'],
  ['src/main.jsx', 'Send RSVP'],
  ['src/main.jsx', 'rsvpAttendance'],
  ['src/main.jsx', 'rsvpEmail'],
  ['src/main.jsx', 'rsvpPhone'],
  ['src/main.jsx', 'rsvpPartySize'],
  ['src/main.jsx', 'rsvpNeeds'],
  ['src/main.jsx', 'parseGuestImport'],
  ['src/main.jsx', 'guestImportKey'],
  ['src/main.jsx', 'importGuestList'],
  ['src/main.jsx', 'Paste Guest List'],
  ['src/main.jsx', 'Import guests'],
  ['src/main.jsx', 'guestInviteText'],
  ['src/main.jsx', 'pendingInvitePacket'],
  ['src/main.jsx', 'Copy pending invites'],
  ['src/main.jsx', 'copy-invite'],
  ['src/styles.css', '.guest-import-panel'],
  ['src/styles.css', '.guest-import-actions'],
  ['src/styles.css', '.guest-list-actions'],
  ['src/styles.css', '.copy-invite'],
  ['src/main.jsx', 'inviteSent'],
  ['src/main.jsx', 'toggleGuestInvite'],
  ['src/main.jsx', 'Guest contacts'],
  ['src/main.jsx', 'guest contact, group, and invite tracking'],
  ['src/main.jsx', 'toggleGuestFollowUp'],
  ['src/main.jsx', 'Guest follow-up updated'],
  ['src/main.jsx', 'guest needs and RSVP follow-up status'],
  ['src/main.jsx', 'getLaunchChecks'],
  ['src/main.jsx', 'getLaunchSnapshot'],
  ['src/main.jsx', 'getLaunchPath'],
  ['src/main.jsx', 'Review, Pay, Publish, Invite, and Preserve'],
  ['src/main.jsx', 'Launch Snapshot'],
  ['src/main.jsx', 'Story, Guest Care, Sharing, and Preservation'],
  ['src/main.jsx', 'getLaunchIssues'],
  ['src/main.jsx', 'Launch Issues'],
  ['src/main.jsx', 'Guest memories waiting'],
  ['src/main.jsx', 'No launch issues found'],
  ['src/styles.css', '.launch-issues-panel'],
  ['src/styles.css', '.launch-issue'],
  ['README.md', 'Launch Issues panel'],
  ['README.md', 'Sensitive Details Review'],
  ['docs/production-checklist.md', 'Launch Issues panel'],
  ['src/main.jsx', 'getFamilyLaunchGuide'],
  ['src/main.jsx', 'What Matters Next'],
  ['src/main.jsx', 'storyStarters'],
  ['src/main.jsx', 'Story starters'],
  ['src/main.jsx', 'Trust center'],
  ['src/main.jsx', 'Onboarding'],
  ['src/main.jsx', 'Funeral-home path'],
  ['src/main.jsx', 'QRCode.toDataURL'],
  ['src/main.jsx', 'downloadCsv'],
  ['src/main.jsx', 'downloadCalendar'],
  ['src/main.jsx', 'downloadProgram'],
  ['src/main.jsx', 'Service Program'],
  ['src/main.jsx', 'Family Wishes'],
  ['src/main.jsx', 'qr-panel'],
  ['src/main.jsx', 'program-mark'],
  ['src/main.jsx', 'polished printable program'],
  ['src/main.jsx', 'downloadMemoryBook'],
  ['src/main.jsx', 'Download memory book'],
  ['src/main.jsx', 'Story Prompts for Later'],
  ['src/main.jsx', 'printable memory book keepsake'],
  ['src/main.jsx', 'downloadQrCards'],
  ['src/main.jsx', 'Download QR cards'],
  ['src/main.jsx', 'qr-table-cards.html'],
  ['src/main.jsx', 'serviceOrder'],
  ['src/main.jsx', 'programPeople'],
  ['src/main.jsx', 'serviceSelections'],
  ['src/main.jsx', 'addServiceSelection'],
  ['src/main.jsx', 'Order of Service'],
  ['src/main.jsx', 'Program Participants'],
  ['src/main.jsx', 'Readings, Music & Tributes'],
  ['src/main.jsx', 'Readings, Music, and Tributes'],
  ['src/main.jsx', 'downloadGuestGuide'],
  ['src/main.jsx', 'downloadJson={downloadJson}'],
  ['src/main.jsx', 'archive-recorded'],
  ['src/main.jsx', 'Archive export recorded'],
  ['src/main.jsx', 'restoreSite'],
  ['src/main.jsx', 'normalizeMemories'],
  ['src/main.jsx', 'importArchive'],
  ['src/main.jsx', 'escapeHtml'],
  ['src/main.jsx', 'Family Messages'],
  ['src/main.jsx', 'MessageTemplate'],
  ['src/styles.css', '.readiness-panel'],
  ['src/styles.css', '.snapshot-panel'],
  ['src/styles.css', '.snapshot-grid'],
  ['src/styles.css', '.snapshot-card'],
  ['src/styles.css', '.approval-panel'],
  ['src/styles.css', '.approval-checks'],
  ['src/styles.css', '.approval-summary'],
  ['src/styles.css', '.message-card'],
  ['src/styles.css', '.helper-card'],
  ['src/styles.css', '.helper-grid'],
  ['src/styles.css', '.activity-card'],
  ['src/styles.css', '.activity-list'],
  ['src/styles.css', '.external-note'],
  ['src/styles.css', '.care-note'],
  ['src/styles.css', '.livestream-panel'],
  ['src/styles.css', '.public-stream-card'],
  ['src/styles.css', '.stream-meta'],
  ['src/styles.css', '.guest-needs-summary'],
  ['src/styles.css', '.invite-toggle'],
  ['src/styles.css', '.follow-up-toggle'],
  ['src/styles.css', '.guest-faq-editor'],
  ['src/styles.css', '.guest-faq-edit'],
  ['src/styles.css', '.custom-care-list'],
  ['src/styles.css', '.custom-care-edit'],
  ['src/styles.css', '.public-custom-care-list'],
  ['src/styles.css', '.public-custom-care-item'],
  ['src/styles.css', '.public-faq-list'],
  ['src/styles.css', '.public-faq-item'],
  ['src/styles.css', '.day-of-packet'],
  ['src/styles.css', '.day-of-task'],
  ['src/styles.css', '.rsvp-box'],
  ['src/styles.css', '.memory-photo-upload'],
  ['src/styles.css', '.photo-tools'],
  ['src/styles.css', '.photo-status'],
  ['src/styles.css', '.photo-thumb.cover'],
  ['src/styles.css', 'figcaption'],
  ['src/styles.css', '.memory-audio-upload'],
  ['src/styles.css', '.audio-attachment'],
  ['src/styles.css', '.consent-check'],
  ['src/styles.css', '.review-consent'],
  ['src/styles.css', '.review-photo'],
  ['src/styles.css', '.review-actions'],
  ['src/styles.css', '.decline'],
  ['src/styles.css', '.moderation-history'],
  ['src/styles.css', '.attendance-options'],
  ['src/styles.css', '.launch-command'],
  ['src/styles.css', '.launch-path'],
  ['src/styles.css', '.launch-path-step'],
  ['src/styles.css', '.launch-report-panel'],
  ['src/styles.css', '.launch-report-grid'],
  ['src/styles.css', '.share-preview-panel'],
  ['src/styles.css', '.share-preview-card'],
  ['src/styles.css', '.meta-grid'],
  ['src/styles.css', '.family-guide'],
  ['src/styles.css', '.story-helper'],
  ['src/styles.css', '.story-prompt-grid'],
  ['src/styles.css', '.integration-panel'],
  ['src/styles.css', '.integration-card'],
  ['src/styles.css', '.accessibility-panel'],
  ['src/styles.css', '.accessibility-checks'],
  ['src/styles.css', '.accessibility-check'],
  ['src/styles.css', '.access-panel'],
  ['src/styles.css', '.access-summary'],
  ['src/styles.css', '.access-gate'],
  ['src/styles.css', '.access-gated'],
  ['src/styles.css', '.archive-panel'],
  ['src/styles.css', '.archive-manifest'],
  ['src/styles.css', '.partner-hero'],
  ['src/styles.css', '.support-edit'],
  ['src/styles.css', '.support-card'],
  ['src/styles.css', '.support-need-list'],
  ['src/styles.css', '.support-need-edit'],
  ['src/styles.css', '.public-need'],
  ['src/styles.css', '.claim-box'],
  ['src/styles.css', '.announcement-card'],
  ['src/styles.css', '.announcement-grid'],
  ['src/styles.css', '.guest-update-list'],
  ['src/styles.css', '.guest-update-edit'],
  ['src/styles.css', '.urgent-update-banner'],
  ['src/styles.css', '.public-update.urgent'],
  ['src/styles.css', '.urgent-toggle'],
  ['src/styles.css', '.obituary-placement-list'],
  ['src/styles.css', '.obituary-placement'],
  ['src/styles.css', '.placement-statuses'],
  ['src/styles.css', '.public-update-list'],
  ['src/styles.css', '.public-update'],
  ['src/styles.css', '.draft-card'],
  ['src/styles.css', '.plan-picker'],
  ['src/styles.css', '.checkout-summary'],
  ['src/styles.css', '.aftercare'],
  ['src/styles.css', '.anniversary-list'],
  ['src/styles.css', '.anniversary-card'],
  ['src/styles.css', '.anniversary-actions'],
  ['src/styles.css', '.thank-you-list'],
  ['src/styles.css', '.thank-you-item'],
  ['src/styles.css', '.aftercare-packet'],
  ['src/styles.css', '.closure-request'],
  ['src/styles.css', '.closure-actions'],
  ['src/styles.css', '.data-safety'],
  ['src/styles.css', '.program-builder'],
  ['src/styles.css', '.program-row'],
  ['src/styles.css', '.service-selection'],
  ['src/styles.css', '.service-selection-list'],
  ['src/styles.css', '.onboarding'],
  ['src/styles.css', '.builder-start-guide'],
  ['src/styles.css', '.builder-start-steps'],
  ['src/styles.css', '.more-tools-grid'],
  ['src/styles.css', '.more-tool-card'],
  ['src/styles.css', '.skip-link'],
  ['src/styles.css', ':focus-visible'],
  ['src/styles.css', '@media (max-width: 860px)'],
  ['.env.example', 'VITE_STRIPE_CHECKOUT_URL'],
  ['.env.example', 'VITE_PUBLISH_ENDPOINT'],
  ['.env.example', 'VITE_INVITE_ENDPOINT'],
  ['.env.example', 'VITE_MEDIA_ENDPOINT'],
  ['.env.example', 'VITE_ACCESS_ENDPOINT'],
  ['.env.example', 'VITE_AUTH_ENDPOINT'],
  ['.env.example', 'VITE_AUDIT_ENDPOINT'],
  ['.env.example', 'VITE_DRAFT_ENDPOINT'],
  ['.env.example', 'VITE_MEMORY_ENDPOINT'],
  ['.env.example', 'VITE_RSVP_ENDPOINT'],
  ['.env.example', 'VITE_SUPPORT_CLAIM_ENDPOINT'],
  ['.env.example', 'AUTH_SECRET'],
  ['.env.example', 'AUTH_FROM_EMAIL'],
  ['.env.example', 'ALLOW_DEMO_AUTH'],
  ['.env.example', 'ALLOW_DEMO_ACCESS'],
  ['.env.example', 'ACCESS_HASH_SECRET'],
  ['.env.example', 'STRIPE_CHECKOUT_URL'],
  ['.env.example', 'STRIPE_SECRET_KEY'],
  ['.env.example', 'STRIPE_FAMILY_PAGE_PRICE_ID'],
  ['.env.example', 'STRIPE_LEGACY_ARCHIVE_PRICE_ID'],
  ['.env.example', 'STRIPE_FUNERAL_HOME_PRICE_ID'],
  ['.env.example', 'STRIPE_WEBHOOK_SECRET'],
  ['.env.example', 'SUPABASE_SERVICE_ROLE_KEY'],
  ['.env.example', 'MEDIA_BUCKET'],
  ['.env.example', 'RESEND_API_KEY'],
  ['.env.example', 'INVITE_FROM_EMAIL'],
  ['.env.example', 'GUEST_NOTIFICATION_FROM_EMAIL'],
  ['.env.example', 'VITE_DEFAULT_MEMORIAL_SLUG'],
  ['api/checkout.js', 'STRIPE_CHECKOUT_URL'],
  ['api/checkout.js', 'STRIPE_SECRET_KEY'],
  ['api/checkout.js', 'checkout/sessions'],
  ['api/checkout.js', "action === 'status'"],
  ['api/checkout.js', 'payment_status'],
  ['api/checkout.js', 'STRIPE_WEBHOOK_SECRET'],
  ['api/checkout.js', 'checkout.session.completed'],
  ['api/checkout.js', 'verifyStripeSignature'],
  ['api/checkout.js', 'persistStripePayment'],
  ['api/checkout.js', 'stripe_checkout_session_id'],
  ['api/checkout.js', 'configuration-needed'],
  ['api/publish.js', 'SUPABASE_SERVICE_ROLE_KEY'],
  ['api/publish.js', 'Launch packet is not ready to publish'],
  ['api/publish.js', 'access_code_hash'],
  ['api/publish.js', 'sanitizeAccessPayload'],
  ['api/publish.js', 'inviteToken'],
  ['api/publish.js', 'checkoutStatus:Paid'],
  ['api/publish.js', 'familyApproval:complete'],
  ['api/publish.js', 'publish_eligible'],
  ['api/publish.js', 'stripe_payment_status'],
  ['api/publish.js', 'payment-required'],
  ['api/publish.js', 'robots_directive'],
  ['api/auth.js', 'Auth packet is not ready'],
  ['api/auth.js', 'configuration-needed'],
  ['api/auth.js', 'AUTH_SECRET'],
  ['api/auth.js', 'issueToken'],
  ['api/auth.js', 'verifyToken'],
  ['api/auth.js', 'persistSession'],
  ['api/auth.js', 'auth_sessions'],
  ['api/auth.js', 'ALLOW_DEMO_AUTH'],
  ['api/auth.js', 'Production auth is not configured'],
  ['api/auth.js', 'timingSafeEqual'],
  ['api/audit.js', 'Audit packet is not ready'],
  ['api/audit.js', 'activity_log'],
  ['api/audit.js', 'configuration-needed'],
  ['api/drafts.js', 'Draft packet needs a slug'],
  ['api/drafts.js', 'draft_payload'],
  ['api/drafts.js', 'archive-export'],
  ['api/drafts.js', 'archive_exports'],
  ['api/drafts.js', 'Archive export recorded'],
  ['api/drafts.js', 'configuration-needed'],
  ['api/memories.js', 'Memory packet is not ready'],
  ['api/memories.js', 'PATCH'],
  ['api/memories.js', 'Memory moderation packet is not ready'],
  ['api/memories.js', 'Memory approved'],
  ['api/memories.js', 'Memory kept private'],
  ['api/memories.js', 'activity_log'],
  ['api/memories.js', 'Pending'],
  ['api/memories.js', 'configuration-needed'],
  ['api/rsvps.js', 'RSVP packet is not ready'],
  ['api/rsvps.js', 'configuration-needed'],
  ['api/support-claims.js', 'Support claim packet is not ready'],
  ['api/support-claims.js', 'configuration-needed'],
  ['src/server/guest-actions.js', 'GUEST_NOTIFICATION_FROM_EMAIL'],
  ['src/server/guest-actions.js', 'patchRows'],
  ['api/access.js', 'Access packet is not ready'],
  ['api/access.js', 'ALLOW_DEMO_ACCESS'],
  ['api/access.js', 'configuration-needed'],
  ['api/access.js', 'SUPABASE_SERVICE_ROLE_KEY'],
  ['api/access.js', 'verifyPasscode'],
  ['src/server/access-hash.js', 'pbkdf2_sha256'],
  ['src/server/access-hash.js', 'ACCESS_HASH_SECRET'],
  ['src/server/access-hash.js', 'timingSafeEqual'],
  ['api/media.js', 'MEDIA_BUCKET'],
  ['api/media.js', 'Media upload packet is not ready'],
  ['api/media.js', 'PATCH'],
  ['api/media.js', 'persistPhotoManifest'],
  ['api/media.js', 'updatePhotoManifest'],
  ['api/media.js', 'manifest-updated'],
  ['api/media.js', 'configuration-needed'],
  ['api/invites.js', 'INVITE_WEBHOOK_URL'],
  ['api/invites.js', 'RESEND_API_KEY'],
  ['api/invites.js', 'Invite packet is not ready to send'],
  ['api/invites.js', 'guest_invites'],
  ['api/invites.js', 'persistInviteRows'],
  ['api/invites.js', 'inviteLedger'],
  ['api/invites.js', 'delivery_status'],
  ['api/invites.js', 'configuration-needed'],
  ['api/health.js', 'integrations'],
  ['api/health.js', 'launchBlocking'],
  ['api/health.js', 'launchReady'],
  ['api/health.js', 'checkSupabaseTable'],
  ['api/health.js', 'auth_sessions'],
  ['api/health.js', 'guest_invites'],
  ['api/health.js', 'photos'],
  ['api/health.js', 'archive_exports'],
  ['api/health.js', 'checkMediaBucket'],
  ['api/health.js', 'checkStripe'],
  ['api/health.js', 'checkResend'],
  ['api/health.js', 'probe'],
  ['api/health.js', '/rest/v1/${table}'],
  ['api/health.js', '/storage/v1/bucket/'],
  ['api/health.js', 'https://api.stripe.com/v1/prices/'],
  ['api/health.js', 'https://api.resend.com/domains'],
  ['api/health.js', 'STRIPE_FAMILY_PAGE_PRICE_ID'],
  ['api/health.js', 'adminAuth'],
  ['api/health.js', 'auditLogging'],
  ['api/health.js', 'draftPersistence'],
  ['api/health.js', 'guestActions'],
  ['api/health.js', 'guestNotifications'],
  ['api/health.js', 'accessControl'],
  ['api/health.js', 'mediaStorage'],
  ['api/health.js', 'inviteDelivery'],
  ['src/main.jsx', "'/api/checkout'"],
  ['src/main.jsx', 'Checkout verified'],
  ['src/main.jsx', 'Needs checkout setup'],
  ['src/main.jsx', "'/api/auth'"],
  ['src/main.jsx', "'/api/audit'"],
  ['src/main.jsx', "'/api/drafts'"],
  ['src/main.jsx', "'/api/memories'"],
  ['src/main.jsx', 'moderateMemory'],
  ['src/main.jsx', "method: 'PATCH'"],
  ['src/main.jsx', "'/api/rsvps'"],
  ['src/main.jsx', "'/api/support-claims'"],
  ['src/main.jsx', "label: 'Start'"],
  ['src/main.jsx', "label: 'Launch'"],
  ['src/main.jsx', 'More Tools'],
  ['src/main.jsx', "'/api/publish'"],
  ['src/main.jsx', "'/api/access'"],
  ['src/main.jsx', "'/api/media'"],
  ['src/main.jsx', 'syncPhotoManifest'],
  ['src/main.jsx', 'updatePhoto'],
  ['src/main.jsx', "'/api/invites'"],
  ['src/main.jsx', 'Publish endpoint needs setup'],
  ['src/main.jsx', 'Verify checkout before publishing'],
  ['index.html', 'site.webmanifest'],
  ['index.html', 'kindred-hero.jpg'],
  ['public/robots.txt', 'Sitemap:'],
  ['public/sitemap.xml', '<urlset'],
  ['public/site.webmanifest', '"name": "Kindred Pages"'],
  ['public/privacy.html', 'Privacy'],
  ['public/terms.html', 'Terms'],
  ['public/security.txt', 'Contact:'],
  ['README.md', 'Production Build'],
  ['README.md', '/api/invites'],
  ['README.md', '/api/media'],
  ['README.md', '/api/access'],
  ['README.md', '/api/auth'],
  ['README.md', '/api/audit'],
  ['README.md', '/api/drafts'],
  ['README.md', 'research-rationale.md'],
  ['README.md', 'storage-integration.md'],
  ['README.md', 'verify:config'],
  ['README.md', 'aftercare packet'],
  ['README.md', 'Launch Snapshot'],
  ['README.md', 'Launch Readiness Report'],
  ['README.md', 'Five-step launch path'],
  ['README.md', 'Builder first-three-decisions guide'],
  ['README.md', 'Guided gathering-type presets'],
  ['README.md', 'Section readiness markers'],
  ['README.md', 'Anniversary care message drafts'],
  ['README.md', 'Day-of service packet'],
  ['README.md', 'Coordinator brief'],
  ['README.md', 'Downloadable polished service program'],
  ['README.md', 'Guest FAQ'],
  ['README.md', 'Custom and ritual care guidance'],
  ['README.md', 'Livestream and replay hub'],
  ['README.md', 'Curated photo gallery'],
  ['README.md', 'Readings, music, and tribute planner'],
  ['README.md', 'Thank-you tracker'],
  ['README.md', 'Closure and data request log'],
  ['README.md', 'guest-needs tracker'],
  ['README.md', 'Guest contact, group, and invite-status tracking'],
  ['README.md', 'Public quick-action bar'],
  ['README.md', 'urgent public banners'],
  ['README.md', 'Paste-import guest list tool'],
  ['README.md', 'Per-guest and pending-invite copy tools'],
  ['README.md', 'Inline public-page confirmations'],
  ['README.md', '/api/memories'],
  ['README.md', '/api/rsvps'],
  ['README.md', '/api/support-claims'],
  ['README.md', 'Guest update center'],
  ['README.md', 'Obituary publication tracker'],
  ['README.md', 'Support needs board'],
  ['README.md', 'Copyable family ownership handoff packet'],
  ['README.md', 'Downloadable printable memory book'],
  ['docs/launch-notes.md', 'Privacy Commitments'],
  ['docs/launch-notes.md', '/api/checkout'],
  ['docs/launch-notes.md', '/api/auth'],
  ['docs/launch-notes.md', '/api/audit'],
  ['docs/launch-notes.md', '/api/drafts'],
  ['docs/launch-notes.md', '/api/memories'],
  ['docs/launch-notes.md', '/api/rsvps'],
  ['docs/launch-notes.md', '/api/support-claims'],
  ['docs/launch-notes.md', '/api/publish'],
  ['docs/launch-notes.md', '/api/access'],
  ['docs/launch-notes.md', '/api/media'],
  ['docs/launch-notes.md', '/api/invites'],
  ['docs/production-checklist.md', 'Production Checklist'],
  ['docs/production-checklist.md', '/api/health'],
  ['docs/production-checklist.md', '/api/auth'],
  ['docs/production-checklist.md', '/api/audit'],
  ['docs/production-checklist.md', '/api/drafts'],
  ['docs/production-checklist.md', '/api/memories'],
  ['docs/production-checklist.md', '/api/rsvps'],
  ['docs/production-checklist.md', '/api/support-claims'],
  ['docs/production-checklist.md', '/api/access'],
  ['docs/production-checklist.md', '/api/media'],
  ['docs/production-checklist.md', '/api/invites'],
  ['docs/production-checklist.md', 'Launch Snapshot'],
  ['docs/production-checklist.md', 'Launch Readiness Report'],
  ['docs/production-checklist.md', 'five-step launch path'],
  ['docs/production-checklist.md', 'gathering-type presets'],
  ['docs/production-checklist.md', 'readiness markers'],
  ['docs/production-checklist.md', 'publish_eligible'],
  ['docs/production-checklist.md', 'first-three-decisions guide'],
  ['docs/production-checklist.md', 'aftercare packet'],
  ['docs/production-checklist.md', 'anniversary care messages'],
  ['docs/production-checklist.md', 'anniversary care message drafts and status'],
  ['docs/production-checklist.md', 'kept-private moderation'],
  ['docs/production-checklist.md', 'PATCH /api/memories'],
  ['docs/production-checklist.md', 'family launch approval'],
  ['docs/production-checklist.md', 'family ownership handoff packet'],
  ['docs/production-checklist.md', 'support-claim, and memory-submission confirmations'],
  ['docs/production-checklist.md', 'public quick-action bar'],
  ['docs/production-checklist.md', 'guest updates'],
  ['docs/production-checklist.md', 'marked urgent'],
  ['docs/production-checklist.md', 'day-of service packet'],
  ['docs/production-checklist.md', 'coordinator brief copies'],
  ['docs/production-checklist.md', 'guest FAQ'],
  ['docs/production-checklist.md', 'custom and ritual care guidance'],
  ['docs/production-checklist.md', 'custom, ritual, faith, and family guidance'],
  ['docs/production-checklist.md', 'livestream and replay hub'],
  ['docs/production-checklist.md', 'livestream platform, replay, recording, and backup plan'],
  ['docs/production-checklist.md', 'guest needs'],
  ['docs/production-checklist.md', 'email, phone, group, invite status'],
  ['docs/production-checklist.md', 'pasted guest lists import'],
  ['docs/production-checklist.md', 'per-guest and pending-invite copy tools'],
  ['docs/production-checklist.md', 'guest_invites'],
  ['docs/production-checklist.md', 'ALLOW_DEMO_AUTH'],
  ['docs/production-checklist.md', 'cover-photo selection'],
  ['docs/production-checklist.md', 'photo manifest rows'],
  ['docs/production-checklist.md', 'readings, music, tributes'],
  ['docs/production-checklist.md', 'QR memory link'],
  ['docs/production-checklist.md', 'thank-you tracker'],
  ['docs/production-checklist.md', 'closure and data requests'],
  ['docs/production-checklist.md', 'archive_exports'],
  ['docs/production-checklist.md', 'obituary placement tracker'],
  ['docs/production-checklist.md', 'support needs'],
  ['docs/production-checklist.md', 'Privacy & Sharing Review'],
  ['docs/production-checklist.md', 'privacy and sharing review notes'],
  ['docs/production-checklist.md', 'Sensitive Details Review'],
  ['docs/production-checklist.md', 'sensitive details review notes'],
  ['docs/production-checklist.md', 'memory book downloads'],
  ['docs/production-checklist.md', 'printable memory book keepsake'],
  ['docs/storage-integration.md', 'Storage Integration'],
  ['docs/storage-integration.md', 'VITE_DRAFT_ENDPOINT'],
  ['docs/storage-integration.md', 'POST /api/drafts'],
  ['docs/storage-integration.md', 'Media Upload Planning'],
  ['docs/storage-integration.md', 'MEDIA_BUCKET'],
  ['docs/research-rationale.md', 'Research Rationale'],
  ['docs/research-rationale.md', 'dual process model'],
  ['docs/backend-contract.md', 'Required API Operations'],
  ['docs/backend-contract.md', 'Included Vercel Function Targets'],
  ['docs/backend-contract.md', 'SUPABASE_SERVICE_ROLE_KEY'],
  ['docs/backend-contract.md', 'memorial_members'],
  ['docs/backend-contract.md', 'partner_account_members'],
  ['docs/backend-contract.md', 'row-level security'],
  ['docs/backend-contract.md', 'GET /api/checkout'],
  ['docs/backend-contract.md', 'POST /api/checkout'],
  ['docs/backend-contract.md', 'STRIPE_SECRET_KEY'],
  ['docs/backend-contract.md', 'STRIPE_WEBHOOK_SECRET'],
  ['docs/backend-contract.md', 'Checkout Session status'],
  ['docs/backend-contract.md', 'POST /api/auth'],
  ['docs/backend-contract.md', 'auth_sessions'],
  ['docs/backend-contract.md', 'signed, expiring admin sign-in links'],
  ['docs/backend-contract.md', 'ALLOW_DEMO_ACCESS'],
  ['docs/backend-contract.md', 'POST /api/audit'],
  ['docs/backend-contract.md', 'GET /api/drafts'],
  ['docs/backend-contract.md', 'POST /api/drafts'],
  ['docs/backend-contract.md', 'archive_exports'],
  ['docs/backend-contract.md', 'POST /api/memories'],
  ['docs/backend-contract.md', 'PATCH /api/memories'],
  ['docs/backend-contract.md', 'POST /api/rsvps'],
  ['docs/backend-contract.md', 'POST /api/support-claims'],
  ['docs/backend-contract.md', 'POST /api/publish'],
  ['docs/backend-contract.md', 'publish_eligible'],
  ['docs/backend-contract.md', 'verified paid checkout'],
  ['docs/backend-contract.md', 'POST /api/access'],
  ['docs/backend-contract.md', 'ACCESS_HASH_SECRET'],
  ['docs/backend-contract.md', 'raw passcodes are not stored'],
  ['docs/backend-contract.md', 'POST /api/media'],
  ['docs/backend-contract.md', 'PATCH /api/media'],
  ['docs/backend-contract.md', 'photo manifest'],
  ['docs/backend-contract.md', 'POST /api/invites'],
  ['docs/backend-contract.md', 'guest_invites'],
  ['docs/backend-contract.md', 'per-recipient delivery status'],
  ['docs/backend-contract.md', 'launch_approval'],
  ['docs/backend-contract.md', 'privacy_review'],
  ['docs/backend-contract.md', 'sensitive_review'],
  ['docs/backend-contract.md', 'Sensitive-details review state'],
  ['docs/backend-contract.md', 'gathering_type'],
  ['docs/backend-contract.md', 'livestream_plan'],
  ['docs/backend-contract.md', 'approved_at'],
  ['docs/backend-contract.md', 'guest_updates'],
  ['docs/backend-contract.md', 'anniversary_care'],
  ['docs/backend-contract.md', 'day_of_checklist'],
  ['docs/backend-contract.md', 'guest_faq'],
  ['docs/backend-contract.md', 'custom_care'],
  ['docs/backend-contract.md', 'obituary_placements'],
  ['docs/backend-contract.md', 'support_needs'],
  ['docs/backend-contract.md', 'follow_up_done'],
  ['docs/backend-contract.md', 'invite_sent'],
  ['docs/backend-contract.md', 'guest_group'],
  ['docs/backend-contract.md', 'is_cover'],
  ['docs/backend-contract.md', 'rejected_at'],
  ['docs/backend-contract.md', 'review_note'],
  ['scripts/verify-config.mjs', 'Production config check'],
  ['scripts/verify-config.mjs', 'STRIPE_CHECKOUT_URL'],
  ['scripts/verify-config.mjs', 'STRIPE_SECRET_KEY'],
  ['scripts/verify-config.mjs', 'STRIPE_FAMILY_PAGE_PRICE_ID'],
  ['scripts/verify-config.mjs', 'STRIPE_WEBHOOK_SECRET'],
  ['scripts/verify-config.mjs', 'SUPABASE_SERVICE_ROLE_KEY'],
  ['scripts/verify-config.mjs', 'VITE_AUTH_ENDPOINT'],
  ['scripts/verify-config.mjs', 'AUTH_SECRET'],
  ['scripts/verify-config.mjs', 'ALLOW_DEMO_AUTH'],
  ['scripts/verify-config.mjs', 'ACCESS_HASH_SECRET'],
  ['scripts/verify-config.mjs', 'VITE_AUDIT_ENDPOINT'],
  ['scripts/verify-config.mjs', 'VITE_MEMORY_ENDPOINT'],
  ['scripts/verify-config.mjs', 'VITE_RSVP_ENDPOINT'],
  ['scripts/verify-config.mjs', 'VITE_SUPPORT_CLAIM_ENDPOINT'],
  ['scripts/verify-config.mjs', 'VITE_ACCESS_ENDPOINT'],
  ['scripts/verify-config.mjs', 'VITE_MEDIA_ENDPOINT'],
  ['scripts/verify-config.mjs', 'MEDIA_BUCKET'],
  ['scripts/verify-config.mjs', 'VITE_INVITE_ENDPOINT'],
  ['scripts/verify-config.mjs', 'RESEND_API_KEY'],
  ['package.json', 'verify:config'],
  ['docs/schema.sql', 'create extension if not exists pgcrypto'],
  ['docs/schema.sql', 'create table memorials'],
  ['docs/schema.sql', 'create table memorial_members'],
  ['docs/schema.sql', 'create table auth_sessions'],
  ['docs/schema.sql', 'auth_sessions_token_hash_idx'],
  ['docs/schema.sql', 'create table partner_account_members'],
  ['docs/schema.sql', 'enable row level security'],
  ['docs/schema.sql', 'current_user_can_manage_memorial'],
  ['docs/schema.sql', 'current_user_can_manage_partner'],
  ['docs/schema.sql', 'public published memorial read'],
  ['docs/schema.sql', 'members manage memorials'],
  ['docs/schema.sql', 'members manage memories'],
  ['docs/schema.sql', 'partners manage drafts'],
  ['docs/schema.sql', 'create table event_schedule'],
  ['docs/schema.sql', 'create table partner_accounts'],
  ['docs/schema.sql', 'status text not null default \'Invited\''],
  ['docs/schema.sql', 'create table partner_drafts'],
  ['docs/schema.sql', 'launch_status'],
  ['docs/schema.sql', 'gathering_type text'],
  ['docs/schema.sql', 'privacy_review jsonb'],
  ['docs/schema.sql', 'sensitive_review jsonb'],
  ['docs/schema.sql', 'livestream_plan jsonb'],
  ['docs/schema.sql', 'invite_token'],
  ['docs/schema.sql', 'allow_guest_sharing'],
  ['docs/schema.sql', 'archive_status'],
  ['docs/schema.sql', 'create table archive_exports'],
  ['docs/schema.sql', 'archive_exports_memorial_id_idx'],
  ['docs/schema.sql', 'closure_status'],
  ['docs/schema.sql', 'closure_requests jsonb'],
  ['docs/schema.sql', 'share_image_url'],
  ['docs/schema.sql', 'canonical_url'],
  ['docs/schema.sql', 'robots_directive text not null default \'noindex,nofollow\''],
  ['docs/schema.sql', 'guest_updates jsonb'],
  ['docs/schema.sql', 'anniversary_care jsonb'],
  ['docs/schema.sql', 'day_of_checklist jsonb'],
  ['docs/schema.sql', 'guest_faq jsonb'],
  ['docs/schema.sql', 'custom_care jsonb'],
  ['docs/schema.sql', 'follow_up_done boolean not null default false'],
  ['docs/schema.sql', 'invite_sent boolean not null default false'],
  ['docs/schema.sql', 'create table guest_invites'],
  ['docs/schema.sql', 'delivery_status text not null default \'Prepared\''],
  ['docs/schema.sql', 'guest_invites_memorial_id_idx'],
  ['docs/schema.sql', 'guest_group text'],
  ['docs/schema.sql', 'is_cover boolean not null default false'],
  ['docs/schema.sql', 'is_public boolean not null default true'],
  ['docs/schema.sql', 'accessibility_checklist jsonb'],
  ['docs/schema.sql', 'plan_price text'],
  ['docs/schema.sql', 'checkout_payload jsonb'],
  ['docs/schema.sql', 'stripe_checkout_session_id text'],
  ['docs/schema.sql', 'stripe_payment_status text'],
  ['docs/schema.sql', 'publish_eligible boolean not null default false'],
  ['docs/schema.sql', 'token_hash text not null'],
  ['docs/schema.sql', 'revoked_at timestamptz'],
  ['docs/schema.sql', 'launch_approval jsonb'],
  ['docs/schema.sql', 'approved_by text'],
  ['docs/schema.sql', 'approved_at timestamptz'],
  ['docs/schema.sql', 'draft_payload'],
  ['docs/schema.sql', 'photo_url'],
  ['docs/schema.sql', 'audio_url'],
  ['docs/schema.sql', 'relation text'],
  ['docs/schema.sql', 'review_consent boolean not null default false'],
  ['docs/schema.sql', 'rejected_at timestamptz'],
  ['docs/schema.sql', 'review_note text'],
  ['docs/schema.sql', 'support_links'],
  ['docs/schema.sql', 'create table support_needs'],
  ['docs/schema.sql', 'support_needs_memorial_id_idx'],
  ['docs/schema.sql', 'create table service_order_items'],
  ['docs/schema.sql', 'create table program_people'],
  ['docs/schema.sql', 'create table service_selections'],
  ['docs/schema.sql', 'service_selections_memorial_id_idx'],
  ['docs/schema.sql', 'create table thank_you_recipients'],
  ['docs/schema.sql', 'thank_you_recipients_memorial_id_idx'],
  ['docs/schema.sql', 'create table obituary_placements'],
  ['docs/schema.sql', 'obituary_placements_memorial_id_idx'],
  ['docs/schema.sql', 'create table activity_log'],
  ['docs/schema.sql', 'activity_log_memorial_id_idx'],
  ['vercel.json', '"outputDirectory": "dist"'],
  ['vercel.json', 'Content-Security-Policy'],
  ['vercel.json', "media-src 'self' data: blob: https:"],
  ['vercel.json', "connect-src 'self' https:"],
  ['vercel.json', "form-action 'self' https:"],
  ['README.md', 'Vercel security headers'],
  ['docs/production-checklist.md', 'production CSP allows approved HTTPS API']
];

const requiredFiles = [
  'assets/kindred-hero.jpg',
  'dist/index.html',
  'dist/site.webmanifest',
  'dist/robots.txt',
  'dist/sitemap.xml',
  'dist/privacy.html',
  'dist/terms.html',
  'dist/security.txt'
];

const failures = [];

for (const [file, needle] of checks) {
  if (!existsSync(join(root, file))) {
    failures.push(`${file} is missing`);
    continue;
  }
  if (!read(file).includes(needle)) {
    failures.push(`${file} does not include ${JSON.stringify(needle)}`);
  }
}

const forbidden = [
  ['src/main.jsx', "setTimeout(() => update('checkoutStatus', 'Paid')"]
];

for (const [file, needle] of forbidden) {
  if (existsSync(join(root, file)) && read(file).includes(needle)) {
    failures.push(`${file} still includes forbidden launch shortcut ${JSON.stringify(needle)}`);
  }
}

for (const file of requiredFiles) {
  if (!existsSync(join(root, file))) {
    failures.push(`${file} is missing`);
  }
}

const distSizeLimit = 900 * 1024;
const heroSizeLimit = 350 * 1024;
const heroFile = 'assets/kindred-hero.jpg';

if (existsSync(join(root, heroFile)) && statSync(join(root, heroFile)).size > heroSizeLimit) {
  failures.push(`${heroFile} exceeds ${heroSizeLimit} bytes`);
}

let distTotal = 0;
for (const file of ['dist/index.html', 'dist/privacy.html', 'dist/terms.html', 'dist/security.txt', 'dist/robots.txt', 'dist/sitemap.xml', 'dist/site.webmanifest']) {
  if (existsSync(join(root, file))) distTotal += statSync(join(root, file)).size;
}
const assetDir = join(root, 'dist/assets');
if (existsSync(assetDir)) {
  for (const name of readdirSync(assetDir)) {
    distTotal += statSync(join(assetDir, name)).size;
  }
}

if (distTotal > distSizeLimit) {
  failures.push(`tracked dist assets exceed ${distSizeLimit} bytes`);
}

if (failures.length) {
  console.error('Launch verification failed:');
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

console.log('Launch verification passed.');
